
name: Action for release
description: Action for release

inputs:
  githubToken:
    description: GitHub token
    required: true
  mode:
    description: Increment mode
    required: false
  flags:
    description: Custom flags
    required: false
    default: ''