name: Action for release
description: Action for release

inputs:
  githubToken:
    description: GitHub token
    required: true

  mode:
    description: Increment mode
    required: false

  flags:
    description: Custom flags
    required: false
    default: ""

outputs:
  released:
    description: was the version updated
    value: ${{ steps.output.outputs.released }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        token: ${{ inputs.githubToken }}
        ref: ${{ inputs.ref || github.ref }}
        persist-credentials: false
        fetch-tags: true
        fetch-depth: 0
    - uses: KimAlexander/release-it/projects/setup-git@main
      with:
        token: ${{ inputs.githubToken }}
    - shell: bash
      id: output
      run: |
        npx release-it ${{ inputs.mode }} --ci ${{ inputs.flags }}
