name: ⚠️ Auto release

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: Bump version as requested
        required: false
        default: minor
        options:
          - patch
          - minor
          - major

jobs:
  run-release:
    name: Release
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest
    steps:
      - name: Check PAT
        env:
          PAT: ${{ secrets.PAT_FOR_BOT }}
        run: |
          if [ -z "$PAT" ]; then
            echo "PAT_FOR_BOT is EMPTY"
            exit 1
          else
            echo "PAT_FOR_BOT is available"
          fi
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: KimAlexander/projects/release-it@main # main
        with:
          mode: ${{ github.event.inputs.mode || 'minor' }}
          githubToken: ${{ secrets.PAT_FOR_BOT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
